#include "bitXor.c"
#include "allOddBits.c"
#include "getByte.c"
#include "reverseBytes.c"
#include "bitMask.c"
#include "bang.c"

#include "isNegative.c"
#include "negate.c"
#include "subOK.c"
#include "isLess.c"
#include "multFiveEighths.c"

#include "float_abs.c"
#include "float_f2i.c"
